# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the Python script to the container
COPY helloworld.py /app/

# Command to run the script
CMD ["python", "helloworld.py"]
